// This file will be auto-generated by Amplify Studio
// For now, we're providing placeholder exports

import { createTheme } from '@aws-amplify/ui-react';

export const studioTheme = createTheme({
  name: 'studioTheme',
  tokens: {
    colors: {
      primary: {
        10: { value: '#e8f0ff' },
        20: { value: '#c5d9ff' },
        40: { value: '#81a7ff' },
        60: { value: '#4a6da7' },
        80: { value: '#3a5a8f' },
        90: { value: '#2a4677' },
        100: { value: '#1a325f' }
      }
    }
  }
});

// Placeholder components that will be generated by Amplify Studio
export const ResearchOpportunityCard = (props) => {
  return null;
};

export const ProfileCard = (props) => {
  return null;
};

export const ApplicationForm = (props) => {
  return null;
};