Parameters:
  env:
    Type: String
  functionnotifyAdminNewUserName:
    Type: String
    Default: functionnotifyAdminNewUserName
  functionnotifyAdminNewUserArn:
    Type: String
    Default: functionnotifyAdminNewUserArn
  functionnotifyAdminNewUserLambdaExecutionRole:
    Type: String
    Default: functionnotifyAdminNewUserLambdaExecutionRole

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${env}-ResearchMarketplace
      LambdaConfig:
        PostConfirmation: !Ref functionnotifyAdminNewUserArn
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
        - Name: given_name
          AttributeDataType: String
          Required: true
        - Name: family_name
          AttributeDataType: String
          Required: true
        - Name: preferred_username
          AttributeDataType: String
          Required: true

  UserPoolPostConfirmationLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref functionnotifyAdminNewUserName
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}'

Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolArn:
    Value: !GetAtt UserPool Arn