/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "emailapi",
            "endpoint": "https://biwbhn48s4.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ybryyyo4mffpfjnpke5773rwxi.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:9a627cc8-5163-4db0-9f52-198770c096d2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_UA7PlngqC",
    "aws_user_pools_web_client_id": "rao5ioafak02qs0dqe6rc8fop",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "researchmarketplace271964ce15f84e66ba7233fe6f91dev-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
