/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b28a23c6-4b15-4d1e-8f8c-45cf891ff3a3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_G1HJcrpJm",
    "aws_user_pools_web_client_id": "7atm26m04kjqcc2vo0q3bkl1mi",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "researchmarketplace4b15d1e02f8c45cf891ff3a382f7f269e-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};

export default awsmobile;