/* eslint-disable */
// This file will be auto-generated by Amplify CLI
// For now, we're providing placeholder exports

export const getUser = /* GraphQL */ `
  query GetUser($id: ID!) {
    getUser(id: $id) {
      id
      username
      email
      name
      type
      major
      year
      interests
      bio
      profilePicture
      createdAt
      updatedAt
    }
  }
`;

export const listUsers = /* GraphQL */ `
  query ListUsers(
    $filter: ModelUserFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listUsers(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        username
        email
        name
        type
        major
        year
        interests
        bio
        profilePicture
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;

export const listResearchOpportunities = /* GraphQL */ `
  query ListResearchOpportunities(
    $filter: ModelResearchOpportunityFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listResearchOpportunities(
      filter: $filter
      limit: $limit
      nextToken: $nextToken
    ) {
      items {
        id
        title
        description
        facultyId
        department
        requirements
        deadline
        startDate
        endDate
        status
        categories
        skills
        createdAt
        updatedAt
      }
      nextToken
    }
  }
`;